# Generated by Django 4.1.6 on 2023-02-12 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="title")),
                ("slug", models.SlugField(unique=True, verbose_name="slug")),
            ],
            options={
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "totale",
                    models.FloatField(blank=True, null=True, verbose_name="totale"),
                ),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "brand",
                    models.ManyToManyField(
                        related_name="products", to="store.brand", verbose_name="brand"
                    ),
                ),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child",
                        to="store.category",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "unique_together": {("slug", "parent")},
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("img", models.CharField(max_length=254, verbose_name="image")),
                ("alt", models.CharField(max_length=50, verbose_name="image alt")),
            ],
            options={
                "verbose_name": "Product Image",
                "verbose_name_plural": "Product Images",
            },
        ),
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="option name")),
            ],
        ),
        migrations.CreateModel(
            name="Shipping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(max_length=250, verbose_name="shipping address"),
                ),
                ("phone", models.IntegerField(verbose_name="phone numbere")),
                ("totalePayed", models.FloatField(verbose_name="totale payed")),
                ("status", models.BooleanField(verbose_name="shipping status")),
                (
                    "payementValiation",
                    models.BooleanField(verbose_name="payement validation"),
                ),
                ("phippingCost", models.FloatField(verbose_name="Shipping cost")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.card",
                        verbose_name="card",
                    ),
                ),
            ],
            options={
                "verbose_name": "shipping",
                "verbose_name_plural": "Shippings",
            },
        ),
        migrations.CreateModel(
            name="ProductOptionValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, verbose_name="value")),
                ("status", models.BooleanField(verbose_name="option status")),
                (
                    "productOption",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productoption",
                        verbose_name="Product Option",
                    ),
                ),
                (
                    "related_img",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.productimage",
                        verbose_name="product option image ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mainImg",
                    models.CharField(max_length=255, verbose_name="main image"),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="prouct status"
                    ),
                ),
                (
                    "liked",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="number of liking"
                    ),
                ),
                ("price", models.FloatField(verbose_name="price")),
                (
                    "discountPrice",
                    models.FloatField(
                        blank=True, null=True, verbose_name="discount price"
                    ),
                ),
                (
                    "category",
                    models.ManyToManyField(
                        related_name="products",
                        to="store.category",
                        verbose_name="catgories",
                    ),
                ),
                (
                    "imgs",
                    models.ManyToManyField(
                        null=True,
                        related_name="products",
                        to="store.productimage",
                        verbose_name="Product Images",
                    ),
                ),
                (
                    "productOptionValues",
                    models.ManyToManyField(
                        null=True,
                        related_name="products",
                        to="store.productoptionvalues",
                        verbose_name="product option values",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="CardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(verbose_name="quantity")),
                (
                    "amount",
                    models.FloatField(blank=True, null=True, verbose_name="amount"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.product",
                        verbose_name="product ordered",
                    ),
                ),
            ],
            options={
                "verbose_name": "CardItem",
                "verbose_name_plural": "CardItems",
            },
        ),
        migrations.AddField(
            model_name="card",
            name="cardItems",
            field=models.ManyToManyField(
                to="store.carditem", verbose_name="Card Items"
            ),
        ),
        migrations.AddField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user card",
            ),
        ),
    ]
